version: '3'

services:
    db:
      build:
        context: ./db
      image: mysql-desafio
      container_name: mysql-desafio
      command: --innodb-use-native-aio=0
      restart: always
      tty: true
      environment:
        - MYSQL_ROOT_PASSWORD=root
      volumes:
      - ./db/data:/var/lib/mysql
      networks:
        - desafio-network

    app:
      build:
        context: ./app
      container_name: app-desafio
      image: app-desafio
      restart: always
      tty: true
      networks:
        - desafio-network
      depends_on:
        - db
    
    nginx:
      build:
        context: ./nginx
      container_name: nginx-desafio
      image: nginx-desafio
      restart: always
      tty: true
      networks:
        - desafio-network
      ports:
        - "8080:80"
      depends_on:
        - app


networks:
  desafio-network:
    driver: bridge